baseURL = "https://yangyuqi22.github.io/"
defaultContentLanguage = "zh"
locale = "zh-CN"
title = "Yuqing's Blog"
theme = "PaperMod"
paginate = 10

[params]
  env = "production"
  defaultTheme = "auto"
  showReadingTime = true
  showShareButtons = false
  showPostNavLinks = true
  showBreadCrumbs = true
  showCodeCopyButtons = true
  showToc = true

  [params.homeInfoParams]
    Title = "Hey 👋"
    Content = "Welcome to my blog"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/yangyuqi22"

[menu]
  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 10
  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 20
  [[menu.main]]
    identifier = "search"
    name = "搜索"
    url = "/search/"
    weight = 30

[outputs]
  home = ["HTML", "RSS", "JSON"]
